name: GitHub Action Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Postman Collection
        uses: postmanlabs/postman-cli-action@v1
        with:
          command: 'collection run 12248282-c7b675af-3ad6-4373-ba6d-7e9a3c83e3c8'
          api-key: ${{ secrets.POSTMAN_API_KEY }}
